name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs: 
  build-docker:
    name: Build and push docker image
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker/docker-compose.yml

    steps:
    - name: Show git ref
      run: echo ${{ github.ref }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker images
      run: docker build -t ghcr.io/hgrf/qtxrpi .

    - name: Login to ghcr
      run: echo ${{ github.token }} | docker login ghcr.io -u hgrf --password-stdin

    - name: Push to ghcr
      run: docker push ghcr.io/hgrf/qtxrpi:latest

    - name: Extract sysroot
      run: |
        make sysroot
        docker image rm ghcr.io/hgrf/qtxrpi:latest
        docker system prune -f

    - name: Get toolchain
      run: make toolchain

    - name: Get Qt5
      run: make download-qt5

    - name: Patch Qt5
      run: make patch-qt5

    - name: Configure Qt5
      run: make configure-qt5
  
    - name: Build Qt5
      run: make build-qt5
    
    - name: List directory and show disk usage
      run: |
        ls -la
        df -h

    - name: Prepare release files
      run: make archive
  
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          qt5.15.tar.gz
          sysroot.tar.gz
