name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs: 
  build-docker:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
    - name: Show git ref
      run: echo ${{ github.ref }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Build docker images
      run: make docker

    - name: Extract sysroot
      run: |
        make sysroot
        docker image rm qtxrpi
        docker system prune -f

    - name: Get toolchain
      run: make toolchain

    - name: Get Qt5
      run: make download-qt5

    - name: Patch Qt5
      run: make patch-qt5

    - name: Configure Qt5
      run: make configure-qt5
  
    - name: Build Qt5
      run: |
        make build-qt5
        rm -rf build
    
    - name: List directory and show disk usage
      run: |
        ls -la
        df -h

    - name: Prepare release files
      run: make archive
  
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          qt5.15.tar.gz
          sysroot.tar.gz

    - name: Create emulator docker image
      run: |
        rm qt5.15.tar.gz
        rm sysroot.tar.gz
        sudo apt install -y sshpass
        make emulator

    - name: Login to ghcr
      run: echo ${{ github.token }} | docker login ghcr.io -u hgrf --password-stdin

    - name: Push to ghcr
      run: |
        GITHUB_TAG=${GITHUB_REF#refs/tags/}
        echo "Tag: ${GITHUB_TAG}"
        docker tag ghcr.io/hgrf/qtxrpi:latest ghcr.io/hgrf/qtxrpi:${GITHUB_TAG}
        docker push ghcr.io/hgrf/qtxrpi:latest
        docker push ghcr.io/hgrf/qtxrpi:${GITHUB_TAG}
  